### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Icelk** [Sollace/Presence-Footsteps#152]
Sometimes, it says two sounds with the same ID are trying to be played.

Here is the top of the error:
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/06/2022, 15:46
Description: Generating PF sounds for entity

java.lang.IllegalArgumentException: duplicate element: mushroom
	at java.base/java.util.ImmutableCollections$Set12.<init>(ImmutableCollections.java:791)
	at java.base/java.util.Set.of(Set.java:704)
	at eu.ha3.presencefootsteps.sound.acoustics.AcousticsPlayer.playAcoustic(AcousticsPlayer.java:29)
	at eu.ha3.presencefootsteps.sound.acoustics.AcousticLibrary.playAcoustic(AcousticLibrary.java:18)
	at eu.ha3.presencefootsteps.world.PFSolver.playAssociation(PFSolver.java:49)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.playSinglefoot(TerrestrialStepSoundGenerator.java:317)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateLanding(TerrestrialStepSoundGenerator.java:277)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateJumpingLanding(TerrestrialStepSoundGenerator.java:251)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateAirborne(TerrestrialStepSoundGenerator.java:225)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.generateFootsteps(TerrestrialStepSoundGenerator.java:76)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$2(SoundEngine.java:118)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$3(SoundEngine.java:116)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at eu.ha3.presencefootsteps.sound.SoundEngine.onFrame(SoundEngine.java:114)
	at eu.ha3.presencefootsteps.PresenceFootsteps.lambda$onTick$1(PresenceFootsteps.java:96)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.PresenceFootsteps.onTick(PresenceFootsteps.java:91)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zfk000$onEndTick(class_310.java:4890)
	at net.minecraft.class_310.method_1574(class_310.java:1869)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


```

**Comment by 6hartmann** [comment]
Seems to be coming from the latest commit. (c43bc04)

If you want to run the mod on 1.19 for now, grab the code from this commit and compile it, works like a charm for me.
https://github.com/Sollace/Presence-Footsteps/tree/0b2d39b38da80e0540f5ae3c3c27acbcd969a98c

**Comment by Icelk** [comment]
Thanks!
