### ISSUE TITLE
The mod doesn't work on server which use custom sound events.

### ISSUE THREAD

**Issue by NoEnd-yt** [Sollace/Presence-Footsteps#154]
I play in 1.19 on Manjaro Linux. Here are the logs:
```
[20:22:12] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received ID map for minecraft:sound_event contains IDs unknown to the receiver!
 - alineamc:music_disc.night_in_venice
 - alineamc:music_disc.anthem_netherlands
 - alineamc:music_disc.anthem_poland
 - alineamc:music_disc.anthem_france
 - alineamc:music_disc.anthem_sweden
 - alineamc:music_disc.anthem_mexico
 - alineamc:music_disc.anthem_slovakia
 - alineamc:music_disc.anthem_australia
 - alineamc:music_disc.anthem_ukraine
 - alineamc:music_disc.vanishing_horizon
 - alineamc:music_disc.anthem_canada
 - alineamc:music_disc.saloon_rag
 - alineamc:music_disc.george_street_shuffle
 - alineamc:music_disc.anthem_usa
 - alineamc:music_disc.anthem_europe
 - alineamc:music_disc.anthem_norway
 - alineamc:music_disc.anthem_belgium
 - alineamc:music_disc.anthem_columbia
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.minecraft.util.registry.SimpleRegistry.remap(SimpleRegistry:704) ~[?:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:314) ~[fabric-registry-sync-v0-0.9.16+92cf9a3ea9-143ca3d3f9c81549.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:125) ~[fabric-registry-sync-v0-0.9.16+92cf9a3ea9-143ca3d3f9c81549.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1095) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:237) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
```

**Comment by NoEnd-yt** [comment]
The issue was caused by another mod, sorry if I pinged anyone.
