### ISSUE TITLE
1.18.2 Crash when entering End City

### ISSUE THREAD

**Issue by XdDJPON3bX** [Sollace/Presence-Footsteps#157]
As said in title, I crash whenever near End Cities. I assume it's because of shulkers making a noise of some kind because that's the only thing I hear for a split second before the crash.

Log:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/26/22, 10:43 PM
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1297.method_5864()" because "entity" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.entity.mob.ShulkerEntity.redirect$hme000$fixTerraformBoatHeightOffset(ShulkerEntity:2877)
	at net.minecraft.entity.mob.ShulkerEntity.getHeightOffset(ShulkerEntity:335)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateBrushes(TerrestrialStepSoundGenerator.java:356)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.generateFootsteps(TerrestrialStepSoundGenerator.java:80)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$1(SoundEngine.java:85)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at eu.ha3.presencefootsteps.sound.SoundEngine.onFrame(SoundEngine.java:82)
	at eu.ha3.presencefootsteps.PresenceFootsteps.lambda$onTick$1(PresenceFootsteps.java:96)
	at java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.PresenceFootsteps.onTick(PresenceFootsteps.java:91)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$dmi000$onEndTick(MinecraftClient:16472)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1817)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1606.redirect$hme000$fixTerraformBoatHeightOffset(class_1606.java:2877)
	at net.minecraft.class_1606.method_5678(class_1606.java:335)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.simulateBrushes(TerrestrialStepSoundGenerator.java:356)
	at eu.ha3.presencefootsteps.sound.generator.TerrestrialStepSoundGenerator.generateFootsteps(TerrestrialStepSoundGenerator.java:80)
	at eu.ha3.presencefootsteps.sound.SoundEngine.lambda$onFrame$1(SoundEngine.java:85)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at eu.ha3.presencefootsteps.sound.SoundEngine.onFrame(SoundEngine.java:82)
	at eu.ha3.presencefootsteps.PresenceFootsteps.lambda$onTick$1(PresenceFootsteps.java:96)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at eu.ha3.presencefootsteps.PresenceFootsteps.onTick(PresenceFootsteps.java:91)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$dmi000$onEndTick(class_310.java:16472)

-- Affected level --
Details:
	All players: 1 total; [class_746['Cephalon_Rose'/92, l='ClientLevel', x=1662.86, y=90.40, z=-1579.30]]
	Chunk stats: 256, 45
	Level dimension: minecraft:the_end
	Level spawn location: World: (64,77,-96), Section: (at 0,13,0 in 4,4,-6; chunk contains blocks 64,0,-96 to 79,383,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,383,-1)
	Level time: 4680057 game time, 4746841 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Sollace** [comment]
Duplicate of #135 .

Update to 1.19. This bug has already been fixed.
