### ISSUE TITLE
(fabric 1.20.4) mod does not work and game crashes when trying to configure it with mod menu

### ISSUE THREAD

**Issue by zmanbro2** [Sollace/Presence-Footsteps#258]
[22:11:28] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.2
[22:11:29] [ForkJoinPool-1-worker-5/WARN]: Mod club_minnced_discord-rpc-release uses the version v3.4.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v3'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:11:29] [main/INFO]: Loading 134 mods:
	- appleskin 2.5.1+mc1.20.3
	   \-- cloth-config 13.0.114
	        \-- cloth-basic-math 0.6.1
	- architectury 11.0.8
	- betterstats 3.6.1+fabric-1.20.4
	   \-- tcdcommons 3.6+fabric-1.20.2
	- c2me 0.2.0+alpha.11.38
	   |-- c2me-base 0.2.0+alpha.11.38
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.38
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.38
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.38
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.38
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.38
	   |-- c2me-notickvd 0.2.0+alpha.11.38
	   |-- c2me-opts-allocs 0.2.0+alpha.11.38
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.38
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.38
	   |-- c2me-opts-math 0.2.0+alpha.11.38
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.38
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.38
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.38
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.38
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.38
	   |-- c2me-server-utils 0.2.0+alpha.11.38
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.38
	   |-- c2me-threading-lighting 0.2.0+alpha.11.38
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.38
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cat_jam 1.2.1
	- cherishedworlds 8.0.0+1.20.4
	- dynamic_fps 3.3.1
	- eatinganimationid 1.20+1.9.5
	- elytratime 2.0.0
	- entityculling 1.6.3.1
	- fabric-api 0.91.3+1.20.4
	   |-- fabric-api-base 0.4.35+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.45+78d798af4f
	   |-- fabric-biome-api-v1 13.0.15+78d798af4f
	   |-- fabric-block-api-v1 1.0.14+78d798af4f
	   |-- fabric-block-view-api-v2 1.0.3+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.45+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.6+78d798af4f
	   |-- fabric-command-api-v1 1.2.40+f71b366f4f
	   |-- fabric-command-api-v2 2.2.19+78d798af4f
	   |-- fabric-commands-v0 0.2.57+df3654b34f
	   |-- fabric-containers-v0 0.1.81+df3654b34f
	   |-- fabric-content-registries-v0 5.0.9+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.9+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.22+78d798af4f
	   |-- fabric-data-generation-api-v1 13.1.17+78d798af4f
	   |-- fabric-dimensions-v1 2.1.60+78d798af4f
	   |-- fabric-entity-events-v1 1.5.28+4ced05924f
	   |-- fabric-events-interaction-v0 0.6.14+78d798af4f
	   |-- fabric-events-lifecycle-v0 0.2.71+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.45+78d798af4f
	   |-- fabric-item-api-v1 2.1.34+78d798af4f
	   |-- fabric-item-group-api-v1 4.0.20+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-keybindings-v0 0.2.38+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.2.29+78d798af4f
	   |-- fabric-loot-api-v2 2.1.4+78d798af4f
	   |-- fabric-message-api-v1 6.0.4+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.59+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.7+78d798af4f
	   |-- fabric-models-v0 0.4.6+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.2+78d798af4f
	   |-- fabric-object-builder-api-v1 13.0.7+78d798af4f
	   |-- fabric-particles-v1 1.1.6+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.15+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.13+78d798af4f
	   |-- fabric-renderer-api-v1 3.2.3+78d798af4f
	   |-- fabric-renderer-indigo 1.5.3+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.50+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.41+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.0.32+78d798af4f
	   |-- fabric-rendering-v0 1.1.53+df3654b34f
	   |-- fabric-rendering-v1 3.0.12+78d798af4f
	   |-- fabric-resource-conditions-api-v1 2.3.13+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.15+78d798af4f
	   |-- fabric-screen-api-v1 2.0.16+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.50+78d798af4f
	   |-- fabric-sound-api-v1 1.0.16+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.6+78d798af4f
	   \-- fabric-transitive-access-wideners-v1 5.0.13+78d798af4f
	- fabricloader 0.15.2
	   \-- mixinextras 0.3.2
	- fallingleaves 1.15.4
	- ferritecore 6.0.3
	- glowing-torchflower 1.0.0
	- iris 1.6.14
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- itemscroller 0.22.0
	- java 20
	- journeymap 5.9.20
	   \-- journeymap-api-fabric 1.20.2-1.9-fabric-SNAPSHOT
	- lighty 2.1.2+1.20.3
	- logical_zoom 0.0.22
	- malilib 0.18.0
	- minecraft 1.20.4
	- modmenu 9.0.0-pre.1
	- mru 0.4.0+1.20.4
	- presencefootsteps 1.10.0
	   \-- kirin 1.16.0+1.20.2
	- real-arrow-tip 0.1.0+mc1.20
	- reeses-sodium-options 1.7.0+mc1.20.2-build.97
	- seamless 2.2.1
	- sodium 0.5.5
	- sodium-extra 0.5.3+mc1.20.2-build.114
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sounds 0.4.0+1.20.4
	- spark 1.10.58
	   \-- fabric-permissions-api-v0 0.2-SNAPSHOT
	- starlight 1.1.3+fabric.f5dcd1a
	- status-effect-bars 1.0.4
	- vanillarpc 1.1
	   |-- club_minnced_discord-rpc-release v3.4.0
	   \-- club_minnced_java-discord-rpc 2.0.2
	- voidfog 2.11.1+1.20.2
	   \-- kirin 1.16.0+1.20.2
	- yet_another_config_lib_v3 3.3.1+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
[22:11:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/zache/OneDrive/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:11:29] [main/INFO]: Compatibility level set to JAVA_17
[22:11:29] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.client.uncapvd.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunk_serializer.mixin
[22:11:30] [main/INFO]: Disabling config ioSystem.gcFreeChunkSerializer: Incompatible with architectury@11.0.8 (*) (defined in c2me)
[22:11:30] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunk_serializer.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[22:11:30] [main/INFO]: Disabling com.ishland.c2me.rewrites.chunkio.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[22:11:30] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[22:11:30] [main/INFO]: Disabling com.ishland.c2me.threading.worldgen.mixin
[22:11:30] [main/WARN]: Reference map 'mru-refmap.json' for mru.mixins.json could not be read. If this is a development environment you can ignore this message
[22:11:30] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[22:11:30] [main/INFO]: Loaded configuration file for Sodium Extra: 34 options available, 0 override(s) found
[22:11:30] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[22:11:31] [main/WARN]: Error loading class: dev/emi/emi/screen/EmiScreenManager (java.lang.ClassNotFoundException: dev/emi/emi/screen/EmiScreenManager)
[22:11:31] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[22:11:31] [main/WARN]: Error loading class: net/caffeinemc/sodium/config/user/UserConfigCategories (java.lang.ClassNotFoundException: net/caffeinemc/sodium/config/user/UserConfigCategories)
[22:11:31] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[22:11:31] [main/INFO]: Searching for graphics cards...
[22:11:31] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[22:11:32] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce GTX 1660, version=DriverVersion=31.0.15.4633]
[22:11:32] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=AMD, name=AMD Radeon(TM) Graphics, version=DriverVersion=31.0.12042.4]
[22:11:32] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[22:11:32] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[22:11:37] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 182 milliseconds
[22:11:40] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[22:11:40] [Render thread/INFO]: Setting user: zmanbro
[22:11:40] [Render thread/INFO]: Initialised
[22:11:41] [Render thread/INFO]: Initializing ServerSide Packet Registries
[22:11:41] [Render thread/INFO]: Registering S2C receiver with id architectury:spawn_entity_packet
[22:11:41] [Render thread/INFO]: Initializing 'Better Statistics Screen' as 'BetterStatsClient'.
[22:11:41] [Render thread/INFO]: Initialised on client
[22:11:41] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[22:11:41] [Render thread/INFO]: Let there be Lighty
[22:11:41] [Worker-Main-1/INFO]: Checking mod updates...
[22:11:42] [Render thread/INFO]: Deserializing UISoundConfig from 'C:\Users\zache\OneDrive\Desktop\MultiMC\instances\1.20.4\.minecraft\config\sounds.ui.config.json'
[22:11:42] [Render thread/INFO]: Deserializing GameplaySoundConfig from 'C:\Users\zache\OneDrive\Desktop\MultiMC\instances\1.20.4\.minecraft\config\sounds.gameplay.config.json'
[22:11:42] [Render thread/INFO]: Deserializing CompatConfig from 'C:\Users\zache\OneDrive\Desktop\MultiMC\instances\1.20.4\.minecraft\config\sounds.mods.config.json'
[22:11:42] [Render thread/INFO]: Initializing 'TCD Commons API' 3.6+fabric-1.20.2 as 'TCDCommonsClient'.
[22:11:43] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[22:11:43] [Render thread/WARN]: Applying workaround: Prevent the NVIDIA OpenGL driver from using broken optimizations (NVIDIA_THREADED_OPTIMIZATIONS)
[22:11:43] [ForkJoinPool.commonPool-worker-1/WARN]: [Iris Update Check] This version doesn't have an update index, skipping.
[22:11:43] [Render thread/INFO]: OpenGL Vendor: NVIDIA Corporation
[22:11:43] [Render thread/INFO]: OpenGL Renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
[22:11:43] [Render thread/INFO]: OpenGL Version: 3.2.0 NVIDIA 546.33
[22:11:43] [Render thread/INFO]: Debug functionality is disabled.
[22:11:43] [Render thread/INFO]: ARB_direct_state_access detected, enabling DSA.
[22:11:43] [Render thread/INFO]: Shaders are disabled because no valid shaderpack is selected
[22:11:43] [Render thread/INFO]: Shaders are disabled
[22:11:44] [Render thread/INFO]: Hardware information:
[22:11:44] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 5600G with Radeon Graphics 
[22:11:44] [Render thread/INFO]: GPU: NVIDIA GeForce GTX 1660/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 546.33)
[22:11:44] [Render thread/INFO]: OS: Windows 11 (10.0)
[22:11:45] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (appleskin, betterstats, c2me, caffeineconfig, cat_jam, cherishedworlds, cloth-config, dynamic_fps, eatinganimationid, elytratime, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fallingleaves, glowing-torchflower, iris, itemscroller, journeymap, lighty, logical_zoom, malilib, modmenu, presencefootsteps, real-arrow-tip, reeses-sodium-options, seamless, sodium, sodium-extra, sounds, spark, starlight, status-effect-bars, tcdcommons, vanillarpc, voidfog, yet_another_config_lib_v3)
[22:11:45] [Worker-Main-4/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[22:11:45] [Render thread/INFO]: Initializing ClientSide Packet Registries
[22:11:45] [Render thread/INFO]: No plugins for JourneyMap API discovered.
[22:11:49] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[22:11:49] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[22:11:49] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Headset Earphone (HyperX Virtual Surround Sound)
[22:11:49] [Render thread/INFO]: Sound engine started
[22:11:50] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[22:11:50] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[22:11:50] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22:11:50] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22:11:50] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[22:11:50] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[22:11:50] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22:11:50] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22:11:50] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22:11:50] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[22:11:50] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[22:11:50] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22:11:50] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22:11:50] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[22:11:51] [Render thread/INFO]: Creating pipeline for dimension NamespacedId{namespace='minecraft', name='overworld'}
[22:12:26] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.2.jar:?]
	at dynamic_fps.impl.util.event.InputObserver.onPress(InputObserver.java:96) ~[dynamic-fps-3.3.1+minecraft-1.20.0.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3509) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:238) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1352) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.2.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: class com.minelittlepony.common.client.gui.element.Button overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at eu.ha3.presencefootsteps.PFOptionsScreen.method_25426(PFOptionsScreen.java:42) ~[PresenceFootsteps-1.10.0.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1187) ~[client-intermediary.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.openConfig(ModListEntry.java:120) ~[modmenu-9.0.0-pre.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.method_25402(ModListEntry.java:110) ~[modmenu-9.0.0-pre.1.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.method_25402(ModListWidget.java:262) ~[modmenu-9.0.0-pre.1.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 22 more
[22:12:27] [Render thread/INFO]: Clearing 'BetterStatsClientNetworkHandler' flags.

**Comment by Sollace** [comment]
Install the 1.20.4 version of Kirin or wait for an update.
