### ISSUE TITLE
Hello, guys, help me please.

### ISSUE THREAD

**Issue by AnpyHelp** [Sollace/Presence-Footsteps#38]
Hello, guys, I have a problem with Presence-Footsteps. 
This is from latest.log:
=============
java.lang.NullPointerException: Unexpected error
at eu.ha3.mc.presencefootsteps.mcpackage.implem.AcousticsManager.playStep(AcousticsManager.java:56)
at eu.ha3.mc.presencefootsteps.game.system.PFSolver.playAssociation(PFSolver.java:64)
at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.simulateFootsteps(PFReaderH.java:115)
at eu.ha3.mc.presencefootsteps.game.system.PFReaderH.generateFootsteps(PFReaderH.java:66)
at eu.ha3.mc.presencefootsteps.game.system.PFIsolator.onFrame(PFIsolator.java:51)
at eu.ha3.mc.presencefootsteps.game.system.PFHaddon.onFrame(PFHaddon.java:359)
at eu.ha3.mc.haddon.litemod.LiteBase.onTick(LiteBase.java:99)
at com.mumfrey.liteloader.core.event.HandlerList$Tickable8.onTick(HandlerList$Tickable8.java:100)
at com.mumfrey.liteloader.client.ClientEvents.onTick(ClientEvents.java:416)
at com.mumfrey.liteloader.client.CallbackProxyClient.onTick(CallbackProxyClient.java:63)
at com.mumfrey.liteloader.core.event.EventProxy.$event00005(EventProxy.java:216)

log file here:

[latest.log](https://github.com/Sollace/Presence-Footsteps/files/4176580/latest.log)

**Comment by Sollace** [comment]
Try removing optifine first.

Since you're on 1.7.10 I can't really help you. I don't support that version of the mod.
